# Review Key Intermediate Python Concepts
1. List comprehensions
2. Lambda functions
3. `*args` and `**kwargs`
4. Operator overloading

# Heading
## Smaller header
**bold text**

## For loops and list comprehensions

In [29]:
results = []
for book in ['Harry Potter', 'War and Peace', 'Power of Habit']:
    if 'Harry' not in book:
        results.append(book)

Let's do it in a list comprehension way.

In [30]:
BOOKS = ['Harry Potter', 'War and Peace', 'Power of Habit']
results = [book for book in BOOKS if 'Harry' not in book]

### Exercise
1. Using a list comprehension, construct a list of all the odd numbers from 1 to 1000.
2. Using a list comprehension, construct a list of the squares of the odd numbers from 1 to 1000.

In [31]:
[i for i in range(1, 1001) if i % 2 == 1]

[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99,
 101,
 103,
 105,
 107,
 109,
 111,
 113,
 115,
 117,
 119,
 121,
 123,
 125,
 127,
 129,
 131,
 133,
 135,
 137,
 139,
 141,
 143,
 145,
 147,
 149,
 151,
 153,
 155,
 157,
 159,
 161,
 163,
 165,
 167,
 169,
 171,
 173,
 175,
 177,
 179,
 181,
 183,
 185,
 187,
 189,
 191,
 193,
 195,
 197,
 199,
 201,
 203,
 205,
 207,
 209,
 211,
 213,
 215,
 217,
 219,
 221,
 223,
 225,
 227,
 229,
 231,
 233,
 235,
 237,
 239,
 241,
 243,
 245,
 247,
 249,
 251,
 253,
 255,
 257,
 259,
 261,
 263,
 265,
 267,
 269,
 271,
 273,
 275,
 277,
 279,
 281,
 283,
 285,
 287,
 289,
 291,
 293,
 295,
 297,
 299,
 301,
 303,
 305,
 307,
 309,
 311,
 313,
 315,
 317,
 319,
 321,
 323,
 325,
 327,
 329,
 331,
 333,
 335,
 337,
 339,
 341,
 343,
 345,
 347,
 349,
 351,
 353,
 355,
 357,
 359,
 361,
 363,
 365,
 367,
 369,
 371,
 373,
 375,
 377,
 379,
 381,
 383,
 385,
 387,
 389,
 391,
 393,
 395,
 397,
 399,
 401,
 403,
 405,
 407,
 409,
 411,
 413,
 415,
 417,
 419,
 421,
 423,
 425,
 427,
 429,
 431,
 433,
 435,
 437,
 439,
 441,
 443,
 445,
 447,
 449,
 451,
 453,
 455,
 457,
 459,
 461,
 463,
 465,
 467,
 469,
 471,
 473,
 475,
 477,
 479,
 481,
 483,
 485,
 487,
 489,
 491,
 493,
 495,
 497,
 499,
 501,
 503,
 505,
 507,
 509,
 511,
 513,
 515,
 517,
 519,
 521,
 523,
 525,
 527,
 529,
 531,
 533,
 535,
 537,
 539,
 541,
 543,
 545,
 547,
 549,
 551,
 553,
 555,
 557,
 559,
 561,
 563,
 565,
 567,
 569,
 571,
 573,
 575,
 577,
 579,
 581,
 583,
 585,
 587,
 589,
 591,
 593,
 595,
 597,
 599,
 601,
 603,
 605,
 607,
 609,
 611,
 613,
 615,
 617,
 619,
 621,
 623,
 625,
 627,
 629,
 631,
 633,
 635,
 637,
 639,
 641,
 643,
 645,
 647,
 649,
 651,
 653,
 655,
 657,
 659,
 661,
 663,
 665,
 667,
 669,
 671,
 673,
 675,
 677,
 679,
 681,
 683,
 685,
 687,
 689,
 691,
 693,
 695,
 697,
 699,
 701,
 703,
 705,
 707,
 709,
 711,
 713,
 715,
 717,
 719,
 721,
 723,
 725,
 727,
 729,
 731,
 733,
 735,
 737,
 739,
 741,
 743,
 745,
 747,
 749,
 751,
 753,
 755,
 757,
 759,
 761,
 763,
 765,
 767,
 769,
 771,
 773,
 775,
 777,
 779,
 781,
 783,
 785,
 787,
 789,
 791,
 793,
 795,
 797,
 799,
 801,
 803,
 805,
 807,
 809,
 811,
 813,
 815,
 817,
 819,
 821,
 823,
 825,
 827,
 829,
 831,
 833,
 835,
 837,
 839,
 841,
 843,
 845,
 847,
 849,
 851,
 853,
 855,
 857,
 859,
 861,
 863,
 865,
 867,
 869,
 871,
 873,
 875,
 877,
 879,
 881,
 883,
 885,
 887,
 889,
 891,
 893,
 895,
 897,
 899,
 901,
 903,
 905,
 907,
 909,
 911,
 913,
 915,
 917,
 919,
 921,
 923,
 925,
 927,
 929,
 931,
 933,
 935,
 937,
 939,
 941,
 943,
 945,
 947,
 949,
 951,
 953,
 955,
 957,
 959,
 961,
 963,
 965,
 967,
 969,
 971,
 973,
 975,
 977,
 979,
 981,
 983,
 985,
 987,
 989,
 991,
 993,
 995,
 997,
 999]

In [32]:
[i ** 2 for i in range(1, 1001) if i % 2 == 1]

[1,
 9,
 25,
 49,
 81,
 121,
 169,
 225,
 289,
 361,
 441,
 529,
 625,
 729,
 841,
 961,
 1089,
 1225,
 1369,
 1521,
 1681,
 1849,
 2025,
 2209,
 2401,
 2601,
 2809,
 3025,
 3249,
 3481,
 3721,
 3969,
 4225,
 4489,
 4761,
 5041,
 5329,
 5625,
 5929,
 6241,
 6561,
 6889,
 7225,
 7569,
 7921,
 8281,
 8649,
 9025,
 9409,
 9801,
 10201,
 10609,
 11025,
 11449,
 11881,
 12321,
 12769,
 13225,
 13689,
 14161,
 14641,
 15129,
 15625,
 16129,
 16641,
 17161,
 17689,
 18225,
 18769,
 19321,
 19881,
 20449,
 21025,
 21609,
 22201,
 22801,
 23409,
 24025,
 24649,
 25281,
 25921,
 26569,
 27225,
 27889,
 28561,
 29241,
 29929,
 30625,
 31329,
 32041,
 32761,
 33489,
 34225,
 34969,
 35721,
 36481,
 37249,
 38025,
 38809,
 39601,
 40401,
 41209,
 42025,
 42849,
 43681,
 44521,
 45369,
 46225,
 47089,
 47961,
 48841,
 49729,
 50625,
 51529,
 52441,
 53361,
 54289,
 55225,
 56169,
 57121,
 58081,
 59049,
 60025,
 61009,
 62001,
 63001,
 64009,
 65025,
 66049,
 67081,
 68121,
 69169,
 70225,
 71289,
 72361,
 73441,
 74529,
 75625,
 76729,
 77841,
 78961,
 80089,
 81225,
 82369,
 83521,
 84681,
 85849,
 87025,
 88209,
 89401,
 90601,
 91809,
 93025,
 94249,
 95481,
 96721,
 97969,
 99225,
 100489,
 101761,
 103041,
 104329,
 105625,
 106929,
 108241,
 109561,
 110889,
 112225,
 113569,
 114921,
 116281,
 117649,
 119025,
 120409,
 121801,
 123201,
 124609,
 126025,
 127449,
 128881,
 130321,
 131769,
 133225,
 134689,
 136161,
 137641,
 139129,
 140625,
 142129,
 143641,
 145161,
 146689,
 148225,
 149769,
 151321,
 152881,
 154449,
 156025,
 157609,
 159201,
 160801,
 162409,
 164025,
 165649,
 167281,
 168921,
 170569,
 172225,
 173889,
 175561,
 177241,
 178929,
 180625,
 182329,
 184041,
 185761,
 187489,
 189225,
 190969,
 192721,
 194481,
 196249,
 198025,
 199809,
 201601,
 203401,
 205209,
 207025,
 208849,
 210681,
 212521,
 214369,
 216225,
 218089,
 219961,
 221841,
 223729,
 225625,
 227529,
 229441,
 231361,
 233289,
 235225,
 237169,
 239121,
 241081,
 243049,
 245025,
 247009,
 249001,
 251001,
 253009,
 255025,
 257049,
 259081,
 261121,
 263169,
 265225,
 267289,
 269361,
 271441,
 273529,
 275625,
 277729,
 279841,
 281961,
 284089,
 286225,
 288369,
 290521,
 292681,
 294849,
 297025,
 299209,
 301401,
 303601,
 305809,
 308025,
 310249,
 312481,
 314721,
 316969,
 319225,
 321489,
 323761,
 326041,
 328329,
 330625,
 332929,
 335241,
 337561,
 339889,
 342225,
 344569,
 346921,
 349281,
 351649,
 354025,
 356409,
 358801,
 361201,
 363609,
 366025,
 368449,
 370881,
 373321,
 375769,
 378225,
 380689,
 383161,
 385641,
 388129,
 390625,
 393129,
 395641,
 398161,
 400689,
 403225,
 405769,
 408321,
 410881,
 413449,
 416025,
 418609,
 421201,
 423801,
 426409,
 429025,
 431649,
 434281,
 436921,
 439569,
 442225,
 444889,
 447561,
 450241,
 452929,
 455625,
 458329,
 461041,
 463761,
 466489,
 469225,
 471969,
 474721,
 477481,
 480249,
 483025,
 485809,
 488601,
 491401,
 494209,
 497025,
 499849,
 502681,
 505521,
 508369,
 511225,
 514089,
 516961,
 519841,
 522729,
 525625,
 528529,
 531441,
 534361,
 537289,
 540225,
 543169,
 546121,
 549081,
 552049,
 555025,
 558009,
 561001,
 564001,
 567009,
 570025,
 573049,
 576081,
 579121,
 582169,
 585225,
 588289,
 591361,
 594441,
 597529,
 600625,
 603729,
 606841,
 609961,
 613089,
 616225,
 619369,
 622521,
 625681,
 628849,
 632025,
 635209,
 638401,
 641601,
 644809,
 648025,
 651249,
 654481,
 657721,
 660969,
 664225,
 667489,
 670761,
 674041,
 677329,
 680625,
 683929,
 687241,
 690561,
 693889,
 697225,
 700569,
 703921,
 707281,
 710649,
 714025,
 717409,
 720801,
 724201,
 727609,
 731025,
 734449,
 737881,
 741321,
 744769,
 748225,
 751689,
 755161,
 758641,
 762129,
 765625,
 769129,
 772641,
 776161,
 779689,
 783225,
 786769,
 790321,
 793881,
 797449,
 801025,
 804609,
 808201,
 811801,
 815409,
 819025,
 822649,
 826281,
 829921,
 833569,
 837225,
 840889,
 844561,
 848241,
 851929,
 855625,
 859329,
 863041,
 866761,
 870489,
 874225,
 877969,
 881721,
 885481,
 889249,
 893025,
 896809,
 900601,
 904401,
 908209,
 912025,
 915849,
 919681,
 923521,
 927369,
 931225,
 935089,
 938961,
 942841,
 946729,
 950625,
 954529,
 958441,
 962361,
 966289,
 970225,
 974169,
 978121,
 982081,
 986049,
 990025,
 994009,
 998001]

### Exercise
Translate the following into a comprehension.

```python
values = []
for x in range(10):
    inner = []
    for y in range(x):
        inner.append(y*3)
    values.append(inner)
```

In [33]:
[[y*3 for y in range(x)] for x in range(10)]

[[],
 [0],
 [0, 3],
 [0, 3, 6],
 [0, 3, 6, 9],
 [0, 3, 6, 9, 12],
 [0, 3, 6, 9, 12, 15],
 [0, 3, 6, 9, 12, 15, 18],
 [0, 3, 6, 9, 12, 15, 18, 21],
 [0, 3, 6, 9, 12, 15, 18, 21, 24]]

## `lambda` functions

In [34]:
(lambda x: x + 2)(3)

5

In [35]:
def add_two(x):
    return x + 2

### Mini-exercise
Create a lambda function that just returns index=1 of a two-item list.

In [36]:
get_second = lambda x: x[1]

In [37]:
get_second(['first', 'second'])

'second'

In [38]:
records = [['Usual Suspects', 8.5], ['The Matrix', 7.2], ['Good Will Hunting', 9.6], ['Pee-wee Herman', 5.2]]

In [39]:
sorted(records)

[['Good Will Hunting', 9.6],
 ['Pee-wee Herman', 5.2],
 ['The Matrix', 7.2],
 ['Usual Suspects', 8.5]]

### Exercise
1. Sort the list of records by score, descending.
2. Sort and filter out any records less than 7.0 score.

In [40]:
sorted(records, key=lambda x: x[1], reverse=True)

[['Good Will Hunting', 9.6],
 ['Usual Suspects', 8.5],
 ['The Matrix', 7.2],
 ['Pee-wee Herman', 5.2]]

In [41]:
sorted([rec for rec in records if rec[1] >= 7], key=lambda x: x[1], reverse=True)

[['Good Will Hunting', 9.6], ['Usual Suspects', 8.5], ['The Matrix', 7.2]]

### Exercise
Create a function in which you can pass in an arbitrary function and it will apply that to the numbers that are divisible by `divisor` between  `start` and `end`.

For example,

```
def cube(num):
    return num ** 3

apply_func_to_divisble_by(1, 20, 2, cube)
>>> [8, 64, ..., 8000]
```

Note: 8 is 2^3, 64 is 4^3, ...

In [42]:
def apply_func_to_divisible_by(start, end, divisor, func):
    return [func(i) for i in range(start, end) if i % divisor == 0]

In [43]:
apply_func_to_divisible_by(1, 20, 2, lambda val: val ** 3)

[8, 64, 216, 512, 1000, 1728, 2744, 4096, 5832]

## `*args` and `**kwargs`

In [44]:
def add_up(numbers):
    count = 0
    for num in numbers:
        count+= num
    return count

add_up([2, 5, 7, 8])

22

In [45]:
def add_up_with_args(*numbers):
    count = 0
    for num in numbers:
        count+= num
    return count

In [46]:
add_up_with_args(1, 2, 7)

10

In [47]:
add_up_with_args(*[2, 28, 35, -7, 103])

161

See how you can call the below function.

In [48]:
def get_odds(**kwargs):
    start = kwargs.get('start', 1)
    end = kwargs.get('end', 1000)
    nums = range(start, end)
    divisor = kwargs.get('divisor', 2)
    return [n for n in nums if n % divisor == 1]

/api/get-odds?start=5

`params ={"start": 5}`

`get_odds(**params)`

Let's look at structuring and destructuring on the fly.

### Application of `*args` and `**kwargs`

In [49]:
class Animal():
    def __init__(self, name, genus, species, alive=True):
        self.name = name
        self.genus = genus
        self.species = species
        self.alive = alive

In [50]:
class Person(Animal):
    def __init__(self, job, *args, health_level='average', **kwargs):
        self.job = job
        self.health_level = health_level
        super().__init__(*args, **kwargs)

In [51]:
Person('engineer', 'bob', 'homo', 'sapiens')

## Operator overloading

Let's create a class called `DataFrame`.

It should take `data` which is a dictionary where the keys are column names and the values are a list of values for that column.

In [52]:
data = {"age": [50, 25, 79], "name": ["Harry", "Suzy", "Alberto"], "location": ["New York", "San Jose", "Virginia"]}

In [53]:
class DataFrame():
    def __init__(self, data):
        self.data = data

    def __repr__(self):
        return "DataFrame with columns {}".format(','.join(self.data.keys()))
    
    def __getitem__(self, key):
        if isinstance(key, str):
            return self.data[key]
        else:
            return {col: self.data[col] for col in key}

In [54]:
df = DataFrame({"age": [50, 25, 79], "name": ["Harry", "Suzy", "Alberto"], "location": ["New York", "San Jose", "Virginia"]})

In [55]:
df["age"]

[50, 25, 79]

Let's implement a basic `__getitem__` method.

## Exercise
Modify the `__getitem__` to return a dictionary of just the subset of columns if a list is passed in.

In [56]:
df[["age", "name"]]

{'age': [50, 25, 79], 'name': ['Harry', 'Suzy', 'Alberto']}

## (Optional) Exercise
Modify the `__getattr__` to return a DataFrame of just rows based on a Boolean series.